# Telegram API
TELEGRAM_BOT_TOKEN = "YOUR_TELEGRAM_BOT_TOKEN"

# Facebook API
FACEBOOK_ACCESS_TOKEN = "YOUR_FACEBOOK_ACCESS_TOKEN"
FACEBOOK_PAGE_ID = "YOUR_FACEBOOK_PAGE_ID"
FACEBOOK_USER_ID = "FRIEND_USER_ID"  # বন্ধুর Facebook User ID
